[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "72af73322c02b3a822c79ab90d593db0cceb1231"
os = "macos"

    [[aws_c_io.download]]
    sha256 = "5577b692f9cc6a685821fcc0f3e6270f148ea010167fb4b62753259cafa6a195"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.aarch64-apple-darwin.tar.gz"
[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "3de837ff558f0a2d3f2bf3e255850297583f78e3"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "5a270bf70951ff8bc8bde5b6778f4165b0a01d1fb5b6357925660253b1147765"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.aarch64-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "78816624c799697675cbcc267c425075258cc391"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "67b6d60d6bb089b5eb944d736b7640086338c97392b3a6edbff5e89381ff8d67"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.aarch64-linux-musl.tar.gz"
[[aws_c_io]]
arch = "aarch64"
git-tree-sha1 = "0fda95268680ff73960874621f1e58bcaebb2822"
os = "freebsd"

    [[aws_c_io.download]]
    sha256 = "7542885368fc27d3e45dcc41c2d333f13dcaee4333f8ba36791659383031fc24"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.aarch64-unknown-freebsd.tar.gz"
[[aws_c_io]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f563df014ee87587bd43d5d0f8c260acc753a223"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "da4222a8f17e77d33c535fd9f74811c59e55d759e0e7febe97431bc810434b04"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_io]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "50ac1006bdcda51aac148ec6e6a591933d4d5721"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "5fc2bc25a6833390b844abffbb1a7b0fae1f7ef4972bd813dba49e03b40126bb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.armv6l-linux-musleabihf.tar.gz"
[[aws_c_io]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fb41047a3e72ef3c8def02394bf722b0705a3dc2"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "ba9003b50a392a40f10ec7e6d6ff1a6196dafc0320e4506430476af26bce326d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_io]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2db1602a3316c5dcc0cc6b5df8cfa600639fb7c8"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "53eaf89302538d4a5c1d154ee29f72d5312bcc734dcb29f3ad05667035c44e5e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.armv7l-linux-musleabihf.tar.gz"
[[aws_c_io]]
arch = "i686"
git-tree-sha1 = "8536c011585e825cf6844fb4554e5082e5153aa7"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "8485d41877a01969f74df27ed33ff95a4d71ebe8f5fbdfff77ce0ce9747a1d01"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.i686-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "i686"
git-tree-sha1 = "7ea344603167c2f9b1ea1c3ac6111d2160359b45"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "4cf1e7fb26ccda6744a6459c89c5105630621d4da605a4214d913d6d2a35d981"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.i686-linux-musl.tar.gz"
[[aws_c_io]]
arch = "powerpc64le"
git-tree-sha1 = "5bf0c70341df6dd02c9ce3ff59f7eafaf25eeaab"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "4a02bd95ab7210a357ee3632718df97f527a5b8c1b47f1eae69276af18bb4118"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.powerpc64le-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "riscv64"
git-tree-sha1 = "87e2646ffb8a23d0dece33095e064da6723e87c8"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "3c0df661ed4f3f156d85174b1e4a8f9972165f2fe934b4eb0e628dbe4dbbce50"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.riscv64-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "1ae01ee7c598d2408165c1192784f17563db0e3e"
os = "macos"

    [[aws_c_io.download]]
    sha256 = "0aece715e6507fce075ee0ec4df3db40f8003dbc0d6b8b6faa53e0022958ca60"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.x86_64-apple-darwin.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "6f755893f59bc2920821dd157b80ef92a335ce89"
libc = "glibc"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "1caf1761f366045266b7ba4fea5f2e871f10d242552d0260d16ddaddfa5556c5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.x86_64-linux-gnu.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "f0322055f2787682cce686bd826af39fac417870"
libc = "musl"
os = "linux"

    [[aws_c_io.download]]
    sha256 = "7abb6e03de1bfc7b6040b792fcd56100a96cf39254ab25e3e1d6116a6d0f4512"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.x86_64-linux-musl.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "62d59f124acc415aa08a360f5b10018a036c5ddb"
os = "freebsd"

    [[aws_c_io.download]]
    sha256 = "803f07f10453effef8e898f01667a40ae10331f15a997681d67edc7aaee1fd36"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.x86_64-unknown-freebsd.tar.gz"
[[aws_c_io]]
arch = "x86_64"
git-tree-sha1 = "593b8c652008543c48e77d11a20357687a23b946"
os = "windows"

    [[aws_c_io.download]]
    sha256 = "6a4f12d46877ad2f1baf21b69b59adc8b4b0e97e424b68be9617673f17630493"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_io_jll.jl/releases/download/aws_c_io-v0.26.2+0/aws_c_io.v0.26.2.x86_64-w64-mingw32.tar.gz"
